package com.example.moodbloom.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF007AFF)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color( 0xFFFCFDFF)
val md_theme_light_onPrimaryContainer = Color(0xFF191919)
val md_theme_light_secondary = Color(0xFF065258)
val md_theme_light_onSecondary = Color(0xFF007AFF)
val md_theme_light_secondaryContainer = Color(0xFF0469D7)
val md_theme_light_onSecondaryContainer = Color(0xFF0F0F0F)
val md_theme_light_tertiary = Color(0xFF32B2F1)
val md_theme_light_onTertiary = Color(0xFF075258)
val md_theme_light_tertiaryContainer = Color(0xFFE9F9F9)
val md_theme_light_onTertiaryContainer = Color(0xFF075258)
val md_theme_light_error = Color(0xFFF26522)
val md_theme_light_onError = Color(0xFFEC615A)
val md_theme_light_errorContainer = Color(0xFFFEC7C4)
val md_theme_light_onErrorContainer = Color(0xFFE10F0F)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF065258)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF0C0D0D)
val md_theme_light_surfaceVariant = Color(0xFFDADDDC)
val md_theme_light_onSurfaceVariant = Color(0xFF757978)
val md_theme_light_outline = Color(0xFFBDE9DE)
val md_theme_light_inverseOnSurface = Color(0xFFFFFFFF)
val md_theme_light_inverseSurface = Color(0xFF065258)
val md_theme_light_inversePrimary = Color(0xFFFFFFFF)
val md_theme_light_shadow = Color(0xFFE7E7E7)
val md_theme_light_surfaceTint = Color(0xFF545B62)
val md_theme_light_outlineVariant = Color(0xFFD0D3D2)
val md_theme_light_scrim = Color(0xFF030F10)

//Extra Colors
val md_theme_light_placeHolder = Color(0xFF92949E)
val md_theme_light_disable = Color(0xFFDADDDC)
val md_theme_light_onDisable = Color(0xFF757978)
val md_theme_light_disable_outline = Color(0xFFD0D3D2)
val md_theme_light_outline_field= Color(0xFFAEE6D7)
val md_theme_light_home_container= Color(0xFFF6FBFC)
val md_theme_light_tertiary_secondary= Color(0xFF46C6A3)



//dark theme colors

val md_theme_dark_primary = Color(0xFF007AFF)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color( 0xFFFCFDFF)
val md_theme_dark_onPrimaryContainer = Color(0xFF191919)
val md_theme_dark_secondary = Color(0xFF065258)
val md_theme_dark_onSecondary = Color(0xFF007AFF)
val md_theme_dark_secondaryContainer = Color(0xFF0469D7)
val md_theme_dark_onSecondaryContainer = Color(0xFF0F0F0F)
val md_theme_dark_tertiary = Color(0xFF32B2F1)
val md_theme_dark_onTertiary = Color(0xFF075258)
val md_theme_dark_tertiaryContainer = Color(0xFFE9F9F9)
val md_theme_dark_onTertiaryContainer = Color(0xFF075258)
val md_theme_dark_error = Color(0xFFF26522)
val md_theme_dark_onError = Color(0xFFEC615A)
val md_theme_dark_errorContainer = Color(0xFFFEC7C4)
val md_theme_dark_onErrorContainer = Color(0xFFE10F0F)
val md_theme_dark_background = Color(0xFFFFFFFF)
val md_theme_dark_onBackground = Color(0xFF065258)
val md_theme_dark_surface = Color(0xFFFFFFFF)
val md_theme_dark_onSurface = Color(0xFF0C0D0D)
val md_theme_dark_surfaceVariant = Color(0xFFDADDDC)
val md_theme_dark_onSurfaceVariant = Color(0xFF757978)
val md_theme_dark_outline = Color(0xFFBDE9DE)
val md_theme_dark_inverseOnSurface = Color(0xFFFFFFFF)
val md_theme_dark_inverseSurface = Color(0xFF065258)
val md_theme_dark_inversePrimary = Color(0xFFFFFFFF)
val md_theme_dark_shadow = Color(0xFFE7E7E7)
val md_theme_dark_surfaceTint = Color(0xFF545B62)
val md_theme_dark_outlineVariant = Color(0xFFD0D3D2)
val md_theme_dark_scrim = Color(0xFF030F10)